# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bc589470e8400265592d33a69923515caf7800dca28b0d7dacbaf026ea59de503faff9cef947a61aaf959bae070aa1581f291166dc080c56a25c3cbabd5ac89a

test:
  secret_key_base: 12df5bc9c65288eb0e128cf40a68eba3050b1bc60033b8b6166faf709621d0f93e277a38178fb074a80bbcaf1309b8de20f8211b0b941cd7de81a5c7acf8bafc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
